# Copyright 2010 David Roundy, roundyd@physics.oregonstate.edu.
# All rights reserved.

include $(GOROOT)/src/Make.inc

TARG=server

GOFILES=\
	server.go\
	header.go\
	about.go\

include $(GOROOT)/src/Make.cmd
