# Copyright 2010 David Roundy, roundyd@physics.oregonstate.edu.
# All rights reserved.

include $(GOROOT)/src/Make.inc

DEPS=../speech ..

TARG=server

GOFILES=\
	server.go\
	header.go\
	about.go\
	style.go\
	bidbox.go\
	favicon.go\
	bidder.go\
	bidforme.go\
	settings.go\
	cardtemplate.go\
	transitorydata.go\
	speak.go\

include $(GOROOT)/src/Make.cmd
