# Copyright 2010 David Roundy, roundyd@physics.oregonstate.edu.
# All rights reserved.

include $(GOROOT)/src/Make.inc

DEPS=../easysocket ..

TARG=server

GOFILES=\
	server.go\
	clientdata.go\
	home.go\
	header.go\

include $(GOROOT)/src/Make.cmd
