# Copyright 2010 David Roundy, roundyd@physics.oregonstate.edu.
# All rights reserved.

include $(GOROOT)/src/Make.inc

DEPS=../easysocket ../speech ..

TARG=server

GOFILES=\
	server.go\
	clientdata.go\
	home.go\
	analyze-bids.go\
	settings.go\
	header.go\
	cardtemplate.go\
	bidbox.go\
	speak.go style.go favicon.go cookie.go\

include $(GOROOT)/src/Make.cmd
