# Copyright 2010 David Roundy, roundyd@physics.oregonstate.edu.
# All rights reserved.

include $(GOROOT)/src/Make.inc

DEPS=../speech ..

TARG=server

GOFILES=\
	server.go\

include $(GOROOT)/src/Make.cmd
